---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebspodpvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-jiva-default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: nginx
          volumeMounts:
            - mountPath: /var/lib/www/html
              name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: openebspodpvc
            readOnly: false
...